### PR TITLE
add `target_type_key` to specify target type

### PR DESCRIPTION
**Pull request by se-m**
Pull Request Description HERE

(check all that apply)
- [x] tests added
- [x] tests passing
- [x] README updated (if needed)
- [x] README Table of Contents updated (if needed)
- [x] History.md and `version` in gemspec are untouched
- [x] backward compatible
- [ ] feature works in `elasticsearch_dynamic` (not required but recommended)

### CODE REVIEW

**Comment by se-m** [comment]
Feature required. But pull request #151 stuck.

**Comment by pitr** [comment]
Thanks!

**Comment by pitr** [comment]
Version 1.5.0 is out with this change

**Comment by se-m** [comment]
when the new version is out?

**Comment by pitr** [comment]
It's out

**Comment by se-m** [comment]
Thank you.

**Pull request merged**
