### PR TITLE
build(deps): Unpin `faraday` from v1, upgrade to v2

### PR DESCRIPTION
**Pull request by raytung**
DESCRIPTION HERE

(check all that apply)
- [ ] tests added
- [x] tests passing
- [ ] README updated (if needed)
- [ ] README Table of Contents updated (if needed)
- [x] History.md and `version` in gemspec are untouched
- [x] backward compatible
- [ ] feature works in `elasticsearch_dynamic` (not required but recommended)

### CODE REVIEW

**Comment by raytung** [comment]
Thanks @cosmo0920 for helping out on this issue - I believe this is a confluent of issues, and there's a bug with Faraday and its adaptor in Ruby 2.7 (which I've jotted down in the linked issue). I don't think we could drop Ruby 2.7 support at the moment since the latest official Fluentd docker image is running on Ruby 2.7. Interested to hear your thoughts on this one.

**Comment by cosmo0920** [comment]
From the official Fluentd docker image, we already moved to use Ruby 3.1 instead of 2.7.
The left things are still using docker official image that is using Ruby 2.7:
https://github.com/docker-library/official-images/blob/381271cfcf579d69b2a1410594e2926f865d38df/library/fluentd#L6
which is based on https://github.com/fluent/fluentd-docker-image/commit/a9e4cee765c7aaf7876d6fe3282aa565dbcdc2a4.

**Comment by raytung** [comment]
@cosmo0920 ah yes of course, I must be blind. Sounds like this fix should work (if all the tests pass). Thanks for your help!

**Review by cosmo0920 — APPROVED** [review]
A big :+1:

**Comment by cosmo0920** [comment]
@kenhys @ashie Could you release the new version of this plugin if needed?

**Comment by ashie** [comment]
I see, thanks!

**Comment by cosmo0920** [comment]
FYI: Docker library image of Fluentd is now updated to use Fluentd v1.16.0 and Ruby 2.7 images are completely gone!

**Pull request merged**
