### PR TITLE
--add reset connection on error

### PR DESCRIPTION
**Pull request by se-m**
Add option to reset connection on any error.(#213)

(check all that apply)
- [x] tests added
- [x] tests passing
- [x] README updated (if needed)
- [x] README Table of Contents updated (if needed)
- [x] History.md and `version` in gemspec are untouched
- [x] backward compatible
- [x] feature works in `elasticsearch_dynamic` (not required but recommended)

### CODE REVIEW

**Comment by se-m** [comment]
travis-ci problem
tests not passed with fluentd v0.14.9 (even in master)
in v0.14.8 all ok

**Comment by pitr** [comment]
Great. Can you merge in master to get tests passing, and rename it to `reconnect_on_error`

**Comment by pitr** [comment]
thanks!

**Comment by pitr** [comment]
released in 1.9.0

**Pull request merged**
