### PR TITLE
Restructuring ILM related features

### LINKED ISSUE #690: config for daily ILM indices
#### Problem
config for daily indices

#### Steps to replicate
config
```
<match log>
  @type elasticsearch
  host 127.0.0.1
  port 9200
  include_tag_key true
  include_timestamp true
  #time_key @timestamp
  reconnect_on_error true
  reload_on_failure true
  reload_connections false
  request_timeout 120s

  rollover_index true
  index_name test-${tag}
  deflector_alias test-${tag}
  index_prefix test
  application_name ${tag}
  index_date_pattern "now/d"

  template_name test-log
  template_file /etc/td-agent/templates/test-log.json
  customize_template {"index_prefix": "test"}
  #template_overwrite true

  enable_ilm true
  ilm_policy_id 30_days
  ilm_policy { <custom policy> }

  <buffer tag, time>
    @type memory
    timekey 1m
    timekey_wait 0
  </buffer>
</match>
```
#### Expected Behavior or What you need to ask
it create index test-log-2020.01.09-000001 and no create new indices anymore
expected behavior: it create new index each day
how can i setup daily indices?

#### Using Fluentd and ES plugin versions
* ubuntu 18.04
* Bare Metal
* Fluentd v1.0
  * td-agent 1.7.4
* fluent-plugin-elasticsearch version 3.7.1 (via custom Gemfile to have ilm feature) 
* ES 7.x

### LINKED ISSUE #693: Logs not being written to ILM enabled index
(check apply)
- [x] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)

#### Problem
The plugin is creating an index with rollover capability `(logstash-default-2020.01.11-000001)` but logs or not being written to it. Another index is being created `(logstash-2020.01.11)` and logs are going there instead.
...

#### Steps to replicate
my config:

```<match **>
      @type elasticsearch
      #@id out_es
      #@log_level info
      index_name fluentd
      type_name fluentd
      host "#{ENV['FLUENT_ELASTICSEARCH_HOST']}"
      port "#{ENV['FLUENT_ELASTICSEARCH_PORT']}"
      path "#{ENV['FLUENT_ELASTICSEARCH_PATH']}"
      scheme "#{ENV['FLUENT_ELASTICSEARCH_SCHEME'] || 'http'}"
      ssl_verify "#{ENV['FLUENT_ELASTICSEARCH_SSL_VERIFY'] || 'true'}"
      ssl_version "#{ENV['FLUENT_ELASTICSEARCH_SSL_VERSION'] || 'TLSv1'}"
      user "#{ENV['FLUENT_ELASTICSEARCH_USER']}"
      password "#{ENV['FLUENT_ELASTICSEARCH_PASSWORD']}"
      reload_connections "#{ENV['FLUENT_ELASTICSEARCH_RELOAD_CONNECTIONS'] || 'false'}"
      reconnect_on_error "#{ENV['FLUENT_ELASTICSEARCH_RECONNECT_ON_ERROR'] || 'true'}"
      reload_on_failure "#{ENV['FLUENT_ELASTICSEARCH_RELOAD_ON_FAILURE'] || 'true'}"
      log_es_400_reason "#{ENV['FLUENT_ELASTICSEARCH_LOG_ES_400_REASON'] || 'false'}"
      logstash_format true
      # Rollover index configuration
      #logstash_prefix app-logs
      template_name logstash-default
      template_file /fluentd/etc/app_index.template
      rollover_index true
      deflector_alias logstash-default
      ilm_policy_id AppLogsAuto
      enable_ilm true
      <buffer>
        flush_thread_count "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_FLUSH_THREAD_COUNT'] || '8'}"
        flush_interval "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_FLUSH_INTERVAL'] || '5s'}"
        chunk_limit_size "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_CHUNK_LIMIT_SIZE'] || '2M'}"
        queue_limit_length "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_QUEUE_LIMIT_LENGTH'] || '32'}"
        retry_max_interval "#{ENV['FLUENT_ELASTICSEARCH_BUFFER_RETRY_MAX_INTERVAL'] || '30'}"
        retry_forever true
      </buffer>
    </match>
```

#### Expected Behavior or What you need to ask
Logs should be written to the `logstash-default-2020.01.11-000001` index not `logstash-2020.01.11`
...

#### Using Fluentd and ES plugin versions

* OS version
* Kubernetes using the fluentd deamonset https://github.com/fluent/fluentd-kubernetes-daemonset/blob/master/fluentd-daemonset-elasticsearch.yaml. I've created my own docker image using `fluent/fluentd-kubernetes-daemonset:v1.7.4-debian-elasticsearch7-2.2` as the base image adding the `elasticsearch-xpack` gem https://rubygems.org/gems/elasticsearch-xpack/versions/7.4.0
* Fluentd v0.12 or v0.14/v1.0
  * `fluentd 1.7.4`
* Gem list
addressable (2.7.0)
bigdecimal (default: 1.4.1)
bundler (default: 1.17.2, 1.16.2)
cmath (default: 1.0.0)
concurrent-ruby (1.1.5)
cool.io (1.5.4)
csv (default: 3.0.9)
date (default: 2.0.0)
dbm (default: 1.0.0)
dig_rb (1.0.1)
domain_name (0.5.20190701)
e2mmap (default: 0.1.0)
elasticsearch (7.4.0)
elasticsearch-api (7.4.0)
elasticsearch-transport (7.4.0)
elasticsearch-xpack (7.4.0)
etc (default: 1.0.1)
excon (0.71.1)
faraday (0.17.1)
fcntl (default: 1.0.0)
ffi (1.11.3)
ffi-compiler (1.0.1)
fiddle (default: 1.0.0)
fileutils (default: 1.1.0)
fluent-config-regexp-type (1.0.0)
fluent-plugin-concat (2.4.0)
fluent-plugin-detect-exceptions (0.0.13)
fluent-plugin-elasticsearch (3.8.0)
fluent-plugin-grok-parser (2.6.1)
fluent-plugin-json-in-json-2 (1.0.2)
fluent-plugin-kubernetes_metadata_filter (2.3.0)
fluent-plugin-multi-format-parser (1.0.0)
fluent-plugin-prometheus (1.6.1)
fluent-plugin-record-modifier (2.0.1)
fluent-plugin-rewrite-tag-filter (2.2.0)
fluent-plugin-systemd (1.0.2)
fluentd (1.7.4)
forwardable (default: 1.2.0)
gdbm (default: 2.0.0)
http (4.2.0)
http-accept (1.7.0)
http-cookie (1.0.3)
http-form_data (2.1.1)
http-parser (1.2.1)
http_parser.rb (0.6.0)
io-console (default: 0.4.7)
ipaddr (default: 1.2.2)
irb (default: 1.0.0)
json (default: 2.1.0)
kubeclient (4.5.0)
logger (default: 1.3.0)
lru_redux (1.1.0)
matrix (default: 0.1.0)
mime-types (3.3)
mime-types-data (3.2019.1009)
msgpack (1.3.1)
multi_json (1.14.1)
multipart-post (2.1.1)
mutex_m (default: 0.1.0)
netrc (0.11.0)
oj (3.8.1)
openssl (default: 2.1.2)
ostruct (default: 0.1.0)
prime (default: 0.1.0)
prometheus-client (0.9.0)
psych (default: 3.1.0)
public_suffix (4.0.1)
quantile (0.2.1)
rake (13.0.1)
rdoc (default: 6.1.2)
recursive-open-struct (1.1.0)
rest-client (2.1.0)
rexml (default: 3.1.9)
rss (default: 0.2.7)
scanf (default: 1.0.0)
sdbm (default: 1.0.0)
serverengine (2.2.0)
shell (default: 0.7)
sigdump (0.2.4)
stringio (default: 0.0.2)
strptime (0.2.3)
strscan (default: 1.0.0)
sync (default: 0.5.0)
systemd-journal (1.3.3)
thwait (default: 0.1.0)
tracer (default: 0.1.0)
tzinfo (2.0.0)
tzinfo-data (1.2019.3)
unf (0.1.4)
unf_ext (0.0.7.6)
webrick (default: 1.4.2)
yajl-ruby (1.4.1)
zlib (default: 1.0.0)

Index template:
```
  {
      "index_patterns": [
        "logstash-default*"
      ],
      "settings": {
        "index": {
          "number_of_replicas": "2"
        }
      },
      "aliases": {
        "logstash-default": {}
      }
    }
```

### LINKED ISSUE #697: Info Log Spam
(check apply)
- [x] read [the contribution guideline](https://github.com/uken/fluent-plugin-elasticsearch/blob/master/CONTRIBUTING.md)

#### Problem
We're overwriting a template as part of our config and getting a tonne of log spam:

```
2020-01-15 23:23:29 +0000 [info]: #0 [elasticsearch] Template 'elasticsearch-template-es5x.json' overwritten with /etc/fluent/config.d/elasticsearch-template-es5x.json.
2020-01-15 23:23:29 +0000 [info]: #0 [elasticsearch] No index and alias creation action performed because rollover_index is set to 'false'
```

#### Steps to replicate

Config:

```
@id elasticsearch
@type elasticsearch
@log_level info
logstash_format true
template_file /etc/fluent/config.d/elasticsearch-template-es5x.json
template_name elasticsearch-template-es5x.json
template_overwrite true
```

Template:

```
{
  "template" : "logstash-*",
  "version" : 50006,
  "settings" : {
    "index.mapping.total_fields.limit": 10000,
    "index.refresh_interval": "120s",
    "number_of_shards": 2
  },
  "mappings" : {
    "_default_" : {
      "dynamic_templates" : [ {
        "message_field" : {
          "path_match" : "message",
          "match_mapping_type" : "string",
          "mapping" : {
            "type" : "text",
            "norms" : false
          }
        }
      }, {
        "string_fields" : {
          "match" : "*",
          "match_mapping_type" : "string",
          "mapping" : {
            "type" : "text",
            "norms" : false,
            "fields" : {
              "keyword" : { "type": "keyword" }
            }
          }
        }
      } ],
      "properties" : {
        "time": { "type": "date" },
        "@timestamp": { "type": "date" },
        "@version": { "type": "keyword" },
        "pid": { "type": "long" },
        "req": {
          "dynamic": true,
          "properties": {
            "id": { "type": "keyword" }
          }
        },
        "geoip"  : {
          "dynamic": true,
          "properties" : {
            "ip": { "type": "ip" },
            "location" : { "type" : "geo_point" },
            "latitude" : { "type" : "half_float" },
            "longitude" : { "type" : "half_float" }
          }
        }
      }
    }
  }
}
```

#### Expected Behavior or What you need to ask

Prior to updating the plugin to the latest version we were using version 2.6.0, which didn't have this output spam with the same config.

#### Using Fluentd and ES plugin versions

* Bare Metal or within Docker or Kubernetes or others? Docker on Kubernetes
* Fluentd v0.12 or v0.14/v1.0
  * 1.8.0
* ES plugin 3.x.y/2.x.y or 1.x.y
  * 3.8.0

### LINKED ISSUE #700: ILM Config
Does someone have a working ILM configuration incl. rollover with elasticsearch and fluentd? My current configuration works with ilm but after the new index (fluentd-bdrs-000002) has been created the old one(fluentd-bdrs-000001) is still the index which gets the incoming data

fluent.conf
```
  output.conf: |-
    # handle timeout log lines from concat plugin
    <match **>
      @type relabel
      @label @NORMAL
    </match>

    <label @NORMAL>
    <match **>
      @id elasticsearch
      @type elasticsearch
      @log_level "#{ENV['OUTPUT_LOG_LEVEL']}"
      include_tag_key true
      host "#{ENV['OUTPUT_HOST']}"
      port "#{ENV['OUTPUT_PORT']}"
      path "#{ENV['OUTPUT_PATH']}"
      scheme "#{ENV['OUTPUT_SCHEME']}"
      ssl_verify "#{ENV['OUTPUT_SSL_VERIFY']}"
      ssl_version "#{ENV['OUTPUT_SSL_VERSION']}"
{{- if (ne .Values.elasticsearch.typeName "") }}
      type_name "#{ENV['OUTPUT_TYPE_NAME']}"
{{- end }}
{{- if .Values.elasticsearch.auth.enabled }}
      user "#{ENV['OUTPUT_USER']}"
      password "#{ENV['OUTPUT_PASSWORD']}"
{{- end }}
      logstash_format false
      logstash_prefix "#{ENV['LOGSTASH_PREFIX']}"
      index_name fluentd-bdrs-000001
      # Should specify rollover_index as true
      rollover_index true
      enable_ilm true
      reconnect_on_error true
      <buffer>
        @type file
        path /var/log/fluentd-buffers/kubernetes.system.buffer
        flush_mode interval
        retry_type exponential_backoff
        flush_thread_count 2
        flush_interval 5s
        retry_forever
        retry_max_interval 30
        chunk_limit_size "#{ENV['OUTPUT_BUFFER_CHUNK_LIMIT']}"
        queue_limit_length "#{ENV['OUTPUT_BUFFER_QUEUE_LIMIT']}"
        overflow_action block
      </buffer>
    </match>
    </label>
```

```
{
  "fluentd-bdrs-000001" : {
    "aliases" : {
      "fluentd-bdrs" : {
        "is_write_index" : false
      }
    },
    "mappings" : {
      "properties" : {
        "bdrsactivityid" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "dataroomCenterid" : {
          "type" : "long"
        },
        "dataroomid" : {
          "type" : "long"
        },
        "details" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "exception" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "hostbdrs" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "httpMethod" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "is64BitOperatingSystem" : {
          "type" : "boolean"
        },
        "is64BitProcess" : {
          "type" : "boolean"
        },
        "line" : {
          "type" : "long"
        },
        "loglevel" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "machineName" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "memberName" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "message" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "module" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "osVersion" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "performanceprocesscpu" : {
          "type" : "float"
        },
        "performanceprocessmemory" : {
          "type" : "float"
        },
        "performancesystemcpu" : {
          "type" : "float"
        },
        "processid" : {
          "type" : "long"
        },
        "processname" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "requestelapsed" : {
          "type" : "long"
        },
        "requestendISO" : {
          "type" : "date"
        },
        "requeststartISO" : {
          "type" : "date"
        },
        "status" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "statusCode" : {
          "type" : "long"
        },
        "statusDescription" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "tag" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "threadid" : {
          "type" : "long"
        },
        "timestampISO" : {
          "type" : "date"
        },
        "timestampUnix" : {
          "type" : "long"
        },
        "url" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "userAgent" : {
          "type" : "text",
          "fields" : {
            "keyword" : {
              "type" : "keyword",
              "ignore_above" : 256
            }
          }
        },
        "userid" : {
          "type" : "long"
        }
      }
    },
    "settings" : {
      "index" : {
        "lifecycle" : {
          "name" : "fluentd-bdrs_policy",
          "rollover_alias" : "fluentd-bdrs",
          "indexing_complete" : "true"
        },
        "number_of_shards" : "3",
        "provided_name" : "fluentd-bdrs-000001",
        "creation_date" : "1579509454179",
        "number_of_replicas" : "1",
        "uuid" : "ZhwOEyrQSFGyIqmLbxPLrA",
        "version" : {
          "created" : "7050199"
        }
      }
    }
  },
  "fluentd-bdrs-000002" : {
    "aliases" : {
      "fluentd-bdrs" : {
        "is_write_index" : true
      }
    },
    "mappings" : { },
    "settings" : {
      "index" : {
        "lifecycle" : {
          "name" : "fluentd-bdrs_policy",
          "rollover_alias" : "fluentd-bdrs"
        },
        "number_of_shards" : "3",
        "provided_name" : "fluentd-bdrs-000002",
        "creation_date" : "1579511823411",
        "number_of_replicas" : "1",
        "uuid" : "MQGlvPE1Ql-aFIdLqN7_vg",
        "version" : {
          "created" : "7050199"
        }
      }
    }
  }
}

```

### PR DESCRIPTION
**Pull request by cosmo0920**
Related to #685, #690, #693, #697, and #700 .
Fixes #690 
Fixes #693
Fixes #697
Fixes #700

When not using placeholders inside Elasticsearch template related parameter, we shouldn't call template installation methods in `#send_bulk` which also means not to call it inside `#write`.

(check all that apply)
- [x] tests added
- [ ] tests passing
- [ ] README updated (if needed)
- [ ] README Table of Contents updated (if needed)
- [x] History.md and `version` in gemspec are untouched
- [ ] backward compatible
- [ ] feature works in `elasticsearch_dynamic` (not required but recommended)

### CODE REVIEW

**Comment by cosmo0920** [comment]
My bad. logstash_format true should be considered.
This PR is not included the above case.
Closing.

**Comment by cosmo0920** [comment]
I'd rewritten ILM feature related code.
This change should be:

* Obsolete index_prefix parameter which is no more used
* Handle logstash_format in ILM
* In non-logstash_format mode, index_name parameter will be used as ILM target index.
* ILM always needs to set up rollover_index. So, specify rollover_index parameter when using ILM is verbose. Just need to specify enable_ilm as true when using rollover alias on ILM 
* Index rollover feature with deflector_alias should be keep backward compatibility
* In ILM feature without logstash_format, users want to set up rollover indices are point to index_name. 
  * Use index_name automatically in ILM when not using logstash_format

**Comment by cosmo0920** [comment]
I'll be released these changes as v4.0.0 because this PR breaks some backward compatibility.

**Comment by cosmo0920** [comment]
@boenr1  @nerzhul  Could you confirm this patch?
I'm waiting user feedbacks to release the new version.

**Comment by nerzhul** [comment]
hello @cosmo0920 just to ensure easier test, can you provide example of old configuration and the corresponding new configuration ? i should admin that the config is a little bit tricky and i'm not an expert on ruby reading :D

**Comment by cosmo0920** [comment]
```aconf
<match file/**>
      @type copy
      <store>
        @type elasticsearch
        host {{ .Values.elastic.host }}
        port {{ .Values.elastic.port }}
        include_tag_key true
        tag_key @log_name
        flush_interval 10s
        logstash_format false
        logstash_prefix k8s
        index_name k8s
        rollover_index true
        deflector_alias k8s
        enable_ilm true
        ilm_policy_id k8s
        template_name fluentd
        template_file /fluentd/etc/es-template.json
      </store>
    </match>
```

should be:

```aconf
<match file/**>
      @type copy
      <store>
        @type elasticsearch
        host {{ .Values.elastic.host }}
        port {{ .Values.elastic.port }}
        include_tag_key true
        tag_key @log_name
        flush_interval 10s
        logstash_format false
        logstash_prefix k8s
        index_name k8s
        # deflector_alias and rollover_index are needn't specify here.
        enable_ilm true
        ilm_policy_id k8s
        template_name fluentd
        template_file /fluentd/etc/es-template.json
      </store>
    </match>
```

**Pull request merged**
