### PR TITLE
Switching to using excon faraday adapter to remove libcurl dependency.

### PR DESCRIPTION
**Pull request by salekseev**
This is another option. Passes tests but requires performance benchmarking prior to merging. I'll let you know what I find in terms of performance as soon as I'm able to put it under load.

### CODE REVIEW

**Comment by repeatedly** [comment]
Is there a concern for merging this PR? Performance?
If someone has a dataset, I also can check the performance.

**Comment by salekseev** [comment]
We have been running this version in our development environment for about a month now with no apparent issues so it has passed a smoke test. We don't nearly have the throughput in dev that matches our production and I haven't gotten around to making a synthetic benchmark for it yet.

**Comment by dterror** [comment]
Thanks @salekseev, I'll run a simple benchmark, but in principle removing libcurl dep will be for the best.
Can you remove your version and authorship changes to gemspec? I'll merge more PRs before bumping.

**Comment by repeatedly** [comment]
> removing libcurl dep will be for the best.

I agree and elasticsearch plugin doesn't flush events in sub-second interval.
So small performance degression is not huge problem.
If need more performance, then we can consider other library like httpclient.

http://reevoo.github.io/blog/2014/09/12/http-shooting-party/

**Comment by salekseev** [comment]
@dterror, we should be all set with gemspec changes.

@repeatedly, I chose excon based on its feature set and popularity (aliveness) after reading http://www.slideshare.net/HiroshiNakamura/rubyhttp-clients-comparison.

**Comment by dterror** [comment]
thks @salekseev, I'll release a new version this week.

**Comment by repeatedly** [comment]
@salekseev nahi-san, a.k.a author of httpclient gem and this presentation, is my co-woker. So if we hit the problem with excon in the future, we can ask him for choosing other HTTP client :)

@dterror Good! I can't wait new version :+1:

**Comment by dterror** [comment]
@repeatedly new version is out v0.8.0

**Comment by repeatedly** [comment]
@dterror Thanks!

@salekseev Awesome work :+1:

**Pull request merged**
