### PR TITLE
Switch to using curb elasticsearch http transport instead of patron

### PR DESCRIPTION
**Pull request by salekseev**
This will hopefully make things faster (needs benchmarking) and will reduce compatibility issues with newer libcurl and parton gems.

### CODE REVIEW

**Comment by salekseev** [comment]
The tests are failing and need fixing. I'm trying to figure out why.

**Comment by pitr** [comment]
I wish we could move away from libcurl-based games altogether

**Comment by dterror** [comment]
Agree with @pitr

**Comment by salekseev** [comment]
I need to do some benchmarking to see how it compares in performance / mem usage to faraday+patron vs curb vs faraday+excon (for example for pure ruby).

**Comment by salekseev** [comment]
Closed in favor of #93.

**Pull request closed without merging**
