### PR TITLE
Add persistent excon connection

### PR DESCRIPTION
**Pull request by cosmo0920**
DESCRIPTION HERE

(check all that apply)
- [x] tests added
- [x] tests passing
- [ ] README updated (if needed)
- [ ] README Table of Contents updated (if needed)
- [x] History.md and `version` in gemspec are untouched
- [x] backward compatible
- [x] feature works in `elasticsearch_dynamic` (not required but recommended)

### CODE REVIEW

**Comment by BernhardBerbuir** [comment]
Hi I have tested your patch. Unfortunately it did not work.

I have played around a bit and found the solution. The option for enabling a persistent connection must be part of `transport_options`

    transport_options: {
      headers: { 'Content-Type' => @content_type.to_s },
      request: { timeout: @request_timeout },
      ssl: { verify: @ssl_verify, ca_file: @ca_file, version: @ssl_version },
      persistent: @persistent_excon_connection
    },

Then a persistent connection is used by excon. I do not know how to specify the timeout for the keep-alive / persisten connection, but the current solution is sufficient for me.

**Comment by cosmo0920** [comment]
Thanks for trying this!
I'll update these patches.

**Comment by cosmo0920** [comment]
Unfortunately, I didn't success to confirm working with your suggestion.

```diff
diff --git a/lib/fluent/plugin/out_elasticsearch.rb b/lib/fluent/plugin/out_elasticsearch.rb
index b07cf21..82bbf47 100644
--- a/lib/fluent/plugin/out_elasticsearch.rb
+++ b/lib/fluent/plugin/out_elasticsearch.rb
@@ -260,6 +260,12 @@ EOC
       @_es ||= begin
         excon_options = { client_key: @client_key, client_cert: @client_cert, client_key_pass: @client_key_pass}
         adapter_conf = lambda {|f| f.adapter :excon, excon_options }
+        transport_options = {
+          headers: { 'Content-Type' => @content_type.to_s },
+          request: { timeout: @request_timeout },
+          ssl: { verify: @ssl_verify, ca_file: @ca_file, version: @ssl_version },
+        }
+        transport_options.merge!(persistent: @persistent_excon_connection) if @persistent_excon_connection
         transport = Elasticsearch::Transport::Transport::HTTP::Faraday.new(get_connection_options.merge(
                                                                             options: {
                                                                               reload_connections: @reload_connections,
@@ -267,12 +273,7 @@ EOC
                                                                               resurrect_after: @resurrect_after,
                                                                               retry_on_failure: 5,
                                                                               logger: @transport_logger,
-                                                                              transport_options: {
-                                                                                headers: { 'Content-Type' => @content_type.to_s },
-                                                                                request: { timeout: @request_timeout },
-                                                                                ssl: { verify: @ssl_verify, ca_file: @ca_file, version: @ssl_versi
on },
-                                                                                persistent: @persistent_excon_connection
-                                                                              },
+                                                                              transport_options: transport_options,
                                                                               http: {
                                                                                 user: @user,
                                                                                 password: @password
```

I've written the above patch but I've got the following error:


```log
port-6.1.0/lib/elasticsearch/transport/transport/http/faraday.rb:38:in `__build_connection'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/base.rb:138:in `block in __build_connections'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/base.rb:130:in `map'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/base.rb:130:in `__build_connections'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/base.rb:40:in `initialize'
  ~/GitHub/fluent-plugin-elasticsearch/lib/fluent/plugin/out_elasticsearch.rb:270:in `new'
  ~/GitHub/fluent-plugin-elasticsearch/lib/fluent/plugin/out_elasticsearch.rb:270:in `client'
  ~/GitHub/fluent-plugin-elasticsearch/lib/fluent/plugin/elasticsearch_index_template.rb:12:in `template_exists?'
  ~/GitHub/fluent-plugin-elasticsearch/lib/fluent/plugin/elasticsearch_index_template.rb:46:in `template_install'
  ~/GitHub/fluent-plugin-elasticsearch/lib/fluent/plugin/out_elasticsearch.rb:152:in `block in configure'
  ~/GitHub/fluent-plugin-elasticsearch/lib/fluent/plugin/elasticsearch_index_template.rb:22:in `retry_install'
  ~/GitHub/fluent-plugin-elasticsearch/lib/fluent/plugin/out_elasticsearch.rb:151:in `configure'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/fluentd-1.2.4/lib/fluent/plugin.rb:164:in `configure'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/fluentd-1.2.4/lib/fluent/agent.rb:130:in `add_match'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/fluentd-1.2.4/lib/fluent/agent.rb:72:in `block in configure'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/fluentd-1.2.4/lib/fluent/agent.rb:64:in `each'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/fluentd-1.2.4/lib/fluent/agent.rb:64:in `configure'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/fluentd-1.2.4/lib/fluent/root_agent.rb:112:in `configure'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/fluentd-1.2.4/lib/fluent/engine.rb:131:in `configure'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/fluentd-1.2.4/lib/fluent/engine.rb:96:in `run_configure'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/fluentd-1.2.4/lib/fluent/supervisor.rb:795:in `run_configure'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/fluentd-1.2.4/lib/fluent/supervisor.rb:579:in `dry_run'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/fluentd-1.2.4/lib/fluent/supervisor.rb:597:in `supervise'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/fluentd-1.2.4/lib/fluent/supervisor.rb:502:in `run_supervisor'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/fluentd-1.2.4/lib/fluent/command/fluentd.rb:310:in `<top (required)>'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/fluentd-1.2.4/bin/fluentd:8:in `require'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/fluentd-1.2.4/bin/fluentd:8:in `<top (required)>'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/bin/fluentd:23:in `load'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/bin/fluentd:23:in `<top (required)>'
```

**Comment by BernhardBerbuir** [comment]
I do not have any Ruby programming experience so that I don't know why the Ruby runtime is complaining (BTW: you posted the stacktrace but I could not see any error message).

I do not understand why the `transport_options` are externalized. If you want to add the persistent_excon_connection key/value only when `persistent_excon_connection==true` then the stackoverflow article [Building a hash in a conditional way](https://stackoverflow.com/questions/7328647/building-a-hash-in-a-conditional-way) might provide an answer.  
If it is possible to add the option always (e.g. even when `persistent_excon_connection==false`) , then this would be the easiest way.

**Comment by cosmo0920** [comment]
I've got NoMethodError when persistent option in transport_options as you sugessted:

```log
NoMethodError: undefined method `persistent=' for #<Faraday::ConnectionOptions:0x00007fd9cb149310>
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/faraday-0.15.2/lib/faraday/options.rb:30:in `block in update'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/faraday-0.15.2/lib/faraday/options.rb:20:in `each'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/faraday-0.15.2/lib/faraday/options.rb:20:in `update'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/faraday-0.15.2/lib/faraday/options.rb:7:in `from'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/faraday-0.15.2/lib/faraday/connection.rb:61:in `initialize'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/http/faraday.rb:38:in `new'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/http/faraday.rb:38:in `__build_connection'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/base.rb:138:in `block in __build_connections'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/base.rb:130:in `map'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/base.rb:130:in `__build_connections'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/elasticsearch-transport-6.1.0/lib/elasticsearch/transport/transport/base.rb:40:in `initialize'
  ~/GitHub/fluent-plugin-elasticsearch/lib/fluent/plugin/out_elasticsearch.rb:269:in `new'
  ~/GitHub/fluent-plugin-elasticsearch/lib/fluent/plugin/out_elasticsearch.rb:269:in `client'
  ~/GitHub/fluent-plugin-elasticsearch/lib/fluent/plugin/elasticsearch_index_template.rb:12:in `template_exists?'
  ~/GitHub/fluent-plugin-elasticsearch/lib/fluent/plugin/elasticsearch_index_template.rb:46:in `template_install'
  ~/GitHub/fluent-plugin-elasticsearch/lib/fluent/plugin/out_elasticsearch.rb:152:in `block in configure'
  ~/GitHub/fluent-plugin-elasticsearch/lib/fluent/plugin/elasticsearch_index_template.rb:22:in `retry_install'
  ~/GitHub/fluent-plugin-elasticsearch/lib/fluent/plugin/out_elasticsearch.rb:151:in `configure'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/fluentd-1.2.4/lib/fluent/plugin.rb:164:in `configure'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/fluentd-1.2.4/lib/fluent/agent.rb:130:in `add_match'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/fluentd-1.2.4/lib/fluent/agent.rb:72:in `block in configure'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/fluentd-1.2.4/lib/fluent/agent.rb:64:in `each'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/fluentd-1.2.4/lib/fluent/agent.rb:64:in `configure'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/fluentd-1.2.4/lib/fluent/root_agent.rb:112:in `configure'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/fluentd-1.2.4/lib/fluent/engine.rb:131:in `configure'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/fluentd-1.2.4/lib/fluent/engine.rb:96:in `run_configure'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/fluentd-1.2.4/lib/fluent/supervisor.rb:795:in `run_configure'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/fluentd-1.2.4/lib/fluent/supervisor.rb:579:in `dry_run'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/fluentd-1.2.4/lib/fluent/supervisor.rb:597:in `supervise'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/fluentd-1.2.4/lib/fluent/supervisor.rb:502:in `run_supervisor'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/fluentd-1.2.4/lib/fluent/command/fluentd.rb:310:in `<top (required)>'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/fluentd-1.2.4/bin/fluentd:8:in `require'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/gems/fluentd-1.2.4/bin/fluentd:8:in `<top (required)>'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/bin/fluentd:23:in `load'
  ~/GitHub/fluent-plugin-elasticsearch/vendor/bundle/ruby/2.5.0/bin/fluentd:23:in `<top (required)>'
```

**Comment by BernhardBerbuir** [comment]
Faraday does not know anything about the `persistent` option. All it has to do is passing it down to Excon. The call graph looks like:

    fluent-plugin-elasticsearch   # your plugin
      ! (call with transport_options)
      v
    elasticsearch-ruby            # understands transport_options
      ! (call with options)
      v
    faraday
      ! (call with [connection_options](https://github.com/lostisland/faraday/blob/v0.15.2/lib/faraday/adapter/excon.rb#L73))
      v
    excon                         # uses variable connection_options with persistent option

I'm not familiar with Ruby [Hashes](https://docs.ruby-lang.org/en/2.4.0/Hash.html),
but it looks like the parameter passing does not work as expected. Faraday tries to parse the hash and applies some arcane magic (at least I do not understand it), which fails.

Could you try to replace

    transport_options.merge!(persistent: @persistent_excon_connection) if @persistent_excon_connection

with

    transport_options.merge!(:persistent => @persistent_excon_connection) if @persistent_excon_connection

If this does not work I would suggest to use the former version or it might not be necessary to make the persistent option configurable at all as the elasticsearch-ruby documentation recommends `persistent == true` anyway

> Keep in mind, that for optimal performance, you should use a HTTP library which supports persistent ("keep-alive") connections, e.g. Patron or Typhoeus. These libraries are not dependencies of the elasticsearch gems, so be sure to define a dependency in your own application.

**Comment by cosmo0920** [comment]
Faraday validates connection_options with [ConnectionOptions.from(options)](https://github.com/lostisland/faraday/blob/8ba0797af97ae048213b5fc0837b7bf4febefa76/lib/faraday/connection.rb#L61).
And then, passed parameters are checked in [ConnectionOptions](https://github.com/lostisland/faraday/blob/8ba0797af97ae048213b5fc0837b7bf4febefa76/lib/faraday/options.rb#L251-L265)

Faraday::ConnectionOptions can handle `headers`, `request`, and `ssl` options but `persistent` is not permitted.

**Comment by cosmo0920** [comment]
Hmm..., it's bit weird.
EXCON_DEBUG=true can display excon connection information.
And its output says that `persistent == true` when the following excon_option is used:

```ruby
excon_options = { client_key: @client_key, client_cert: @client_cert, client_key_pass: @client_key_pass, persistent: true}
```

```log
excon.request
  :body                => nil
  :chunk_size          => 1048576
  :ciphers             => "ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA:!DSS"
  :client_cert         => nil
  :client_key          => nil
  :client_key_pass     => nil
  :connect_timeout     => 1.0
  :debug_request       => true
  :debug_response      => true
  :headers             => {
    "Content-Type" => "application/json"
    "Host"         => "localhost:9200"
    "User-Agent"   => "Faraday v0.15.2"
  }
  :host                => "localhost"
  :hostname            => "localhost"
  :idempotent          => false
  :instrumentor        => Excon::StandardInstrumentor
  :instrumentor_name   => "excon"
  :method              => "GET"
  :middlewares         => [
    Excon::Middleware::ResponseParser
    Excon::Middleware::Expects
    Excon::Middleware::Idempotent
    Excon::Middleware::Instrumentor
    Excon::Middleware::Mock
  ]
  :mock                => false
  :nonblock            => true
  :omit_default_port   => false
  :path                => "/"
  :persistent          => true #<=== Original Patch makes this options to be true.
  :port                => 9200
  :query               => nil
  :read_timeout        => 1.0
  :retries_remaining   => 4
  :retry_limit         => 4
  :scheme              => "http"
  :ssl_uri_schemes     => [
    "https"
  ]
  :ssl_verify_peer     => true
  :stubs               => :global
  :tcp_nodelay         => false
  :thread_safe_sockets => true
  :uri_parser          => URI
  :versions            => "excon/0.62.0 (x86_64-darwin17) ruby/2.5.1"
  :write_timeout       => 1.0
excon.response
  :body          => "{\n  \"name\" : \"eycK1t_\",\n  \"cluster_name\" : \"elasticsearch_cosmo\",\n  \"cluster_uuid\" : \"4UjvsSZRRvuSJisTu11LLQ\",\n  \"version\" : {\n    \"number\" : \"6.2.4\",\n    \"build_hash\" : \"ccec39f\",\n    \"build_date\" : \"2018-04-12T20:37:28.497551Z\",\n    \"build_snapshot\" : false,\n    \"lucene_version\" : \"7.2.1\",\n    \"minimum_wire_compatibility_version\" : \"5.6.0\",\n    \"minimum_index_compatibility_version\" : \"5.0.0\"\n  },\n  \"tagline\" : \"You Know, for Search\"\n}\n"
  :cookies       => [
  ]
  :headers       => {
    "content-length" => "441"
    "content-type"   => "application/json; charset=UTF-8"
  }
  :host          => "localhost"
  :local_address => "::1"
  :local_port    => 52098
  :path          => "/"
  :port          => 9200
  :reason_phrase => "OK"
  :remote_ip     => "::1"
  :status        => 200
  :status_line   => "HTTP/1.1 200 OK\r\n"
```

**Comment by BernhardBerbuir** [comment]
I have checked the logs of the fluentd plugin and found there the same error (`NoMethodError: undefined method 'persistent='`) as you. Moving the `persistent` option to the `transport_options` made the plugin crash and therefore it did no longer send any message to NGinX and no messages of type `client 10.1.2.3 closed keepalive connection`occurred any more (shame on me not checking the logs earlier)

I have upgraded to the latest released version (2.11.3) of the plugin and applied the changed line at `lib/fluent/plugin/out_elasticsearch_dynamic.rb` you mentioned:

        excon_options = {
          client_key: @client_key,
          client_cert: @client_cert,
          client_key_pass: @client_key_pass,
          persistent: true,
          connect_timeout: 1800
        }

The `excon_options` seems to be the right place to specify the option. Nonetheless there are still a lot of "client closed keepalive connection" messages at the NGinX log. Maybe the duration of the keepalive connection is just a second? I have seen the option `:connect_timeout     => 1.0` in your debug output. I tried to increase it (`connect_timeout: 1800`) it but it did not change anything. Excon supports to configure persistent at connection level __and__ request. Perhaps the request must be changed also?

**Comment by cosmo0920** [comment]
Hmm..., it seems that it is hard to support keepalive connection with excon.
[This approach](https://github.com/uken/fluent-plugin-elasticsearch/commit/e79bb45e7d510f310b1dc29380b74a2df0552b5f) works on your environment?

**Comment by BernhardBerbuir** [comment]
The new approach works. After deploying it I no longer see the message `client 10.1.2.3 closed keepalive connection`
=> great work!

**Comment by cosmo0920** [comment]
Closing this in favor of #456.

**Pull request closed without merging**
